sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Hiu0219
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: sky-xiaoheyu
    access-key-id: LTAI5tQzeM2aUuW5SqwYfX1W
    access-key-secret: v56YtxACUUVFXKMlpQhl9xfDgzdzls
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10