sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Hiu0219
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: sky-xiaoheyu
    access-key-id: LTAI5tQzeM2aUuW5SqwYfX1W
    access-key-secret: v56YtxACUUVFXKMlpQhl9xfDgzdzls
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxa53044f32e36bbee
    secret: 7a8f6d846c7ab75df82058c1665a0496
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
#    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
#    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    notify-url:  http://5f30468c.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: http://5f30468c.r2.cpolar.top/notify/refundSuccess
